### ISSUE TITLE
No preview after vertical stitching.

### ISSUE THREAD

**Issue by The-Droidster** [afollestad/photo-affix#12]

**Comment by The-Droidster** [comment]
Device: Nexus 5 6.0.1

**Comment by afollestad** [comment]
Hmm, it's working fine for me. 
![screener_20160101 01 50 08](https://cloud.githubusercontent.com/assets/1820165/12070160/1042915a-b02a-11e5-80a2-634d6e6a1ae1.png)
I'm guessing you just have to wait longer for the resulting image to load; it'll still be saved to your device, but if you don't downsize them it may take a bit longer to load.
