### ISSUE TITLE
How add admob?

### ISSUE THREAD

**Issue by andrect1** [afollestad/photo-affix#22]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of this app.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - App version: `x.x.x.x`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Redistribution for monetization is not allowed and would result in potential legal action.
