### ISSUE TITLE
Strange Crashing when backing out sometimes

### ISSUE THREAD

**Issue by VirusThePanda** [afollestad/photo-affix#4]
I noticed that when backing out of the app, then going back in (through recent apps), it will sometimes crash. It only happened twice, but I thought it was worth noting

**Comment by afollestad** [comment]
It'll be hard to know what it is without a logcat, although the current codebase now has Crashlytics integrated

**Comment by VirusThePanda** [comment]
I'll give you a logcat. It could be possible that this was my own device messing up and not your app. I will let you know.

**Comment by VirusThePanda** [comment]
Just checked a logcat. Sorry for the false alarm. It was a problem caused by my phone, as it happened with another app as well.
