### ISSUE TITLE
Text gets blurry as images are downsized?

### ISSUE THREAD

**Issue by afollestad** [afollestad/photo-affix#9]
Not sure if you would have an idea about this, @plusCubed?

I noticed it when setting the output scale to 0.25.

**Comment by afollestad** [comment]
If you test it, make sure you have the latest version from commits I just pushed today.

**Comment by plusCubed** [comment]
Hm.. I'm guessing it's a matter of anti-aliasing or resampling. I'll check it out after dinner.

**Comment by afollestad** [comment]
Cool, thanks!

**Comment by plusCubed** [comment]
So I used the techniques described [here by Sony](http://developer.sonymobile.com/2011/06/27/how-to-scale-images-for-your-android-application/), which is basically a two-step process:
1. Decode the Bitmap to the smallest size that is still larger than the desired size - this will sample the image, smooth things out, and as a bonus reduce memory usage.
2. Draw it to a canvas to the actual desired size.

Here's a comparison (the difference is pretty minimal but visible, I "affixed" one image to 15%):
![affix_20151026_200017](https://cloud.githubusercontent.com/assets/6379975/10748596/1a7eb8d6-7c1f-11e5-85d1-0f0c700d7c09.png)
![affix_20151026_200034](https://cloud.githubusercontent.com/assets/6379975/10748602/254488e0-7c1f-11e5-8776-835214624a97.png)

**Comment by plusCubed** [comment]
OK, actually, I just read the issue again, and I realized that I'm not even sure this is the problem you're describing (might be worsening it by resampling the image?)...

**Comment by afollestad** [comment]
That might actually help. But:

Websites like http://picresize.com have no quality loss; I wouldn't expect
making a large image smaller to lose any pixels.

But when I take a very large image (e.g. 6000x3000), and downsize it in
PhotoAffix (e.g. to 2000x1000), the image becomes slightly blurry.
Especially on text. The images are scaled down on the coordinate plane in
MainActivity.

On Mon, Oct 26, 2015, 10:23 PM Daniel Ciao <notifications@github.com> wrote:

> So I used the techniques described here by Sony
> <http://developer.sonymobile.com/2011/06/27/how-to-scale-images-for-your-android-application/>,
> which is basically a two-step process:
> 1. Decode the Bitmap to the smallest size that is still larger than the
> desired size - this will sample the image, smooth things out, and as a
> bonus reduce memory usage.
> 2. Draw it to a canvas to the actual desired size.
>
> Here's a comparison (the difference is pretty minimal but visible, I
> "affixed" one image to 15%):
> [image: affix_20151026_200017]
> <https://cloud.githubusercontent.com/assets/6379975/10748596/1a7eb8d6-7c1f-11e5-85d1-0f0c700d7c09.png>
> [image: affix_20151026_200034]
> <https://cloud.githubusercontent.com/assets/6379975/10748602/254488e0-7c1f-11e5-8776-835214624a97.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/photo-affix/issues/9#issuecomment-151361531>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by plusCubed** [comment]
Hmm....http://stackoverflow.com/questions/16408505/how-to-downsample-images-correctly

**Comment by plusCubed** [comment]
Well, downscaling images is exactly that - losing pixels & information density. We need to interpolate some data to fill in the places where there used to be information. In Photoshop there are many options - bicubic, bilinear, and nearest-neighbor. On Android with Bitmaps by default there is none - it just downscales.

I pushed with two options for downsampling. Both decode the input stream to a small image size by resampling, and while both look better than no interpolation, they don't look as nice as the website's or Photoshop's resampling, so I have no idea what they are (nearest neighbor? bicubic? bilinear? combination?).
1: inSampleSize - Google's recommended way. Downsamples in powers of 2 (probably nearest neighbor), and then we have to downscale (no interpolation) to the accurate size.
2: inDensity - Downsamples to the final size. As the stackoverflow guy observed, seems to use more memory and slower than option 1, but the images are somewhat smoother (might be using bilinear, but either way still not as smooth as Photoshop downsampling).

Those are the built-in Android ways. There's also what the stackoverflow person wrote for [bilinear interpolation](https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations/blob/dc721c5e063e5455c221ed8877446d8485f9bf61/extra/BilinearInterpolation.java) - I'll try those out tomorrow.

**Comment by afollestad** [comment]
Thanks for the commits!

I find it weird that you need to do any of this with downsizing, I thought you only really needed to use interpolation when you scale up. [PicResize](http://www.picresize.com) does a perfect job not losing any quality, it doesn't make you select any filters. While [ImageEnlarger](http://www.imageenlarger.com) has you select different types of filters (like the ones discussed above) to fill in space lost from enlarging pixels. But I guess it makes sense, since you would have to remove pixels in order to compress the image.

**Comment by plusCubed** [comment]
Yeah, in Photoshop there is one resampling option specifically labeled for reduction - "Bicubic Sharper", which seems to produce very nice, sharp results (PicResize probably uses something similar - they don't say what though). After comparing a few photos to the options in Photoshop, it looks like inSampleSize uses bilinear interpolation (in orders of 2). Bilinear seems to work, but softens the image quite a bit. The stackoverflow person's processing seems to come out about the same.

[This](http://entropymine.com/resamplescope/notes/photoshop/) and [this](https://github.com/paulasiimwe/Android-ImageMagick) might be worth looking into. I'm also curious about what Google Photos does if you scale down the image there - I need to try that.
